Cypress.Commands.add('Forms', (formulario) => {    
        cy.get('#nome')
        .type(formulario.username)
        .should('be.visible', formulario.username)
        cy.get('#sobrenome')
        .type(formulario.lastname)
        .should('be.visible', formulario.lastname)
        cy.get('#email')
        .type(formulario.email)
        .should('be.visible',formulario.email)
        cy.get('#pais')
        .type('Brasil')
        .should('have.value' , 'Brasil')
        cy.get('button').click()
        cy.contains('Ação realizada com sucesso').should('be.visible')
      })