Cypress.Commands.add('Forms', (formulario) => {
  cy.get('#nome')
    .type(formulario.username)
    .should('have.value', formulario.username)
  cy.get('#sobrenome')
    .type(formulario.lastname)
    .should('have.value', formulario.lastname)
  cy.get('#email')
    .type(formulario.email)
    .should('have.value', formulario.email)
  cy.get('#pais')
    .type('Brasil')
    .should('have.value', 'Brasil')
  cy.get('button').click()
  cy.contains('Ação realizada com sucesso').should('be.visible')
})